global:
  licencePlate: e3c3c4
  serviceAccountName: default
  envSecretName: ''
  imagePullSecrets: []

app:
  enabled: true
  replicaCount: 1
  crunchydbSecret: hesp-app-db-poc
  dependencyWait:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi
  route:
    enabled: false

sidekiq:
  enabled: false

anycable-rpc:
  enabled: false

crunchy-postgres:
  enabled: false

redis:
  enabled: false

elasticsearch:
  enabled: false

anycableGo:
  enabled: false

clamav:
  enabled: false

nginxProxy:
  enabled: true
  replicas: 1
  upstreamHost: hesp-app
  upstreamPort: 3000
  websocketUpstreamHost: hesp-app
  websocketUpstreamPort: 3000
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  route:
    host: hesp-poc.apps.dev.devops.gov.bc.ca
