global:
  vault:
    role: bfc7dd-nonprod
    subPath: bfc7dd-dev
  env: {}

app:
  enabled: true

  image:
    # repository: artifacts.developer.gov.bc.ca/bbfc-dev/hesp-dev
    repository: ghcr.io/bcgov/hesp-app

  resources:
    requests:
      cpu: 300m
      memory: 512Mi

  env:
    'APP_DOMAIN': 'dev-hesp.apps.silver.devops.gov.bc.ca'
    'SECURE_JWT_COOKIE': 'true'
    'VITE_ENABLE_TEMPLATE_FORCE_PUBLISH': 'true'
    'ENABLE_TEMPLATE_FORCE_PUBLISH': 'true'
    'ANYCABLE_URL': 'wss://dev-hesp-anycable.apps.silver.devops.gov.bc.ca/cable'
    'KEYCLOAK_AUTH_URL': 'https://dev.loginproxy.gov.bc.ca/'
    'VITE_SITEMINDER_LOGOUT_URL': 'https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi'
    'VITE_BCEID_URL': 'https://www.development.bceid.ca'
    'VITE_BUSINESS_BCEID_REGISTRATION_URL': 'https://www.development.bceid.ca/register/business/getting_started/getting_started.aspx'
    'VITE_KEYCLOAK_LOGOUT_URL': 'https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout'
    'VITE_POST_LOGOUT_REDIRECT_URL': 'https://dev-hesp.apps.silver.devops.gov.bc.ca'
    # File Upload Configuration 
    'BCGOV_OBJECT_STORAGE_REGION': 'ca-central-1'
    'BCGOV_OBJECT_STORAGE_ENDPOINT': 'https://s3.ca-central-1.amazonaws.com'
    'BCGOV_OBJECT_STORAGE_PUBLIC_ENDPOINT': 'https://s3.ca-central-1.amazonaws.com'
    'BCGOV_OBJECT_STORAGE_BUCKET': 'pbmmaccel-fffbffdev3d903d-phase1-cacentral1-rhvwcsmaejxv'
    # ClamAV Configuration - Disabled for now
    'CLAMAV_ENABLED': 'false'
    'CLAMAV_HOST': 'clamav'
    'CLAMAV_PORT': '3310'
    'CLAMAV_TIMEOUT': '30'
    'VIRUS_SCAN_TEMP_DIR': '/tmp/virus_scan'
    'UPLOAD_VIRUS_SCAN_TIMEOUT': '45'

  route:
    enabled: true
    host: dev-hesp.apps.silver.devops.gov.bc.ca

sidekiq:
  enabled: true

  image:
    # repository: artifacts.developer.gov.bc.ca/bbfc-dev/hesp-dev
    repository: ghcr.io/bcgov/hesp-app

  resources:
    requests:
      cpu: 100m
      memory: 256Mi

  env:
    'APP_DOMAIN': 'dev-hesp.apps.silver.devops.gov.bc.ca'
    'FROM_EMAIL': 'no-reply@gov.bc.ca'
    # File Upload Configuration 
    'BCGOV_OBJECT_STORAGE_REGION': 'ca-central-1'
    'BCGOV_OBJECT_STORAGE_ENDPOINT': 'https://s3.ca-central-1.amazonaws.com'
    'BCGOV_OBJECT_STORAGE_PUBLIC_ENDPOINT': 'https://s3.ca-central-1.amazonaws.com'
    'BCGOV_OBJECT_STORAGE_BUCKET': 'pbmmaccel-fffbffdev3d903d-phase1-cacentral1-rhvwcsmaejxv'
    # ClamAV Configuration - Disabled for now
    'CLAMAV_ENABLED': 'false'
    'CLAMAV_HOST': 'clamav'
    'CLAMAV_PORT': '3310'
    'CLAMAV_TIMEOUT': '30'
    'VIRUS_SCAN_TEMP_DIR': '/tmp/virus_scan'
    'UPLOAD_VIRUS_SCAN_TIMEOUT': '45'

anycable-rpc:
  enabled: true

  image:
    # repository: artifacts.developer.gov.bc.ca/bbfc-dev/hesp-dev
    repository: ghcr.io/bcgov/hesp-app

  nameOverride: hesp-anycable-rpc
  fullnameOverride: hesp-anycable-rpc

  resources:
    requests:
      cpu: 50m
      memory: 128Mi

  env:
    # File Upload Configuration 
    'BCGOV_OBJECT_STORAGE_REGION': 'ca-central-1'
    'BCGOV_OBJECT_STORAGE_ENDPOINT': 'https://s3.ca-central-1.amazonaws.com'
    'BCGOV_OBJECT_STORAGE_PUBLIC_ENDPOINT': 'https://s3.ca-central-1.amazonaws.com'
    'BCGOV_OBJECT_STORAGE_BUCKET': 'pbmmaccel-fffbffdev3d903d-phase1-cacentral1-rhvwcsmaejxv'

crunchy-postgres:
  enabled: true

  instances:
    replicas: 1
    dataVolumeClaimSpec:
      storage: 1Gi
    requests:
      cpu: 10m
      memory: 256Mi
    replicaCertCopy:
      requests:
        cpu: 10m
        memory: 32Mi

  pgBackRest:
    retention: '1'
    repos:
      volume:
        storage: 256Mi
    repoHost:
      requests:
        cpu: 1m
        memory: 64Mi
    sidecars:
      requests:
        cpu: 1m
        memory: 64Mi

  patroni:
    postgresql:
      pg_hba:
        - 'host all all ::1/128 md5' #allow connections for developers to port foward
        - 'host all all 0.0.0.0/0 md5'
      parameters:
        shared_buffers: 16MB # default is 128MB; a good tuned default for shared_buffers is 25% of the memory allocated to the pod
        wal_buffers: 64kB # this can be set to -1 to automatically set as 1/32 of shared_buffers or 64kB, whichever is larger
        min_wal_size: 32MB
        max_wal_size: 64MB # default is 1GB
        max_slot_wal_keep_size: 128MB # default is -1, allowing unlimited wal growth when replicas fall behind

  proxy:
    pgBouncer:
      image: # it's not necessary to specify an image as the images specified in the Crunchy Postgres Operator will be pulled by default
      replicas: 2
      requests:
        cpu: 50m
        memory: 64Mi

  # Postgres Cluster resource values:
  pgmonitor:
    enabled: false
    exporter:
      image: # it's not necessary to specify an image as the images specified in the Crunchy Postgres Operator will be pulled by default
      requests:
        cpu: 1m
        memory: 64Mi

# See https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
redis:
  enabled: true

  sentinel:
    resources:
      requests:
        memory: 128Mi
        cpu: 20m
  replica:
    replicaCount: 1
    persistence:
      enabled: true
      size: 500Mi
    resources:
      requests:
        memory: 128Mi
        cpu: 20m

# See https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/values.yaml
elasticsearch:
  enabled: true

  master:
    replicaCount: 1
    heapSize: 128m
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 500Mi
  data:
    replicaCount: 1
    heapSize: 1024m
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi

# See https://github.com/anycable/anycable-helm/blob/master/anycable-go/values.yaml
anycableGo:
  enabled: true

  route:
    enabled: true
    host: dev-hesp-anycable.apps.silver.devops.gov.bc.ca

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
