apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "_.fullname" . }}
  labels:
    {{- include "_.labels" . | nindent 4 }}
  # No special AWS annotations needed - using direct IAM user credentials
automountServiceAccountToken: true