addAllBuiltIn: false  # Do not auto-add all built-ins, so config is deterministic
checks:
  include:
    - privileged-container
    - latest-tag
  exclude:
    - ssh-port               # if you want to ignore that
    - dangling-service
    - no-read-only-root-fs
    - run-as-non-root
    - unset-cpu-requirements
    - unset-memory-requirements
