redis:
  sentinel:
    resources:
      requests:
        memory: "128Mi"
        cpu: "20m"
      limits:
        memory: "256Mi"
        cpu: "50m"
  replica:
    replicaCount: 1
    persistence:
      enabled: true
      size: 500Mi
    resources:
      requests:
        memory: "128Mi"
        cpu: "20m"
      limits:
        memory: "256Mi"
        cpu: "100m"