redis:
  sentinel:
    resources:
      requests:
        memory: "48Mi"
        cpu: "50m"
      limits:
        memory: "96Mi"
        cpu: "100m"
  replica:
    replicaCount: 1
    persistence:
      enabled: true
      size: 500Mi
    resources:
      requests:
        memory: "96Mi"
        cpu: "150m"
      limits:
        memory: "192Mi"
        cpu: "200m"