apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clamav.fullname" . }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
data:
  clamd.conf: |-
{{ .Files.Get "configurations/clamd.conf" | indent 4 }}
  freshclam.conf: |-
{{ .Files.Get "configurations/freshclam.conf" | indent 4 }}
