apiVersion: v1
kind: Service
metadata:
  name: {{ include "_.fullname" . }}
  labels:
    {{- include "_.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp-50051
      protocol: TCP
      name: tcp-50051
  selector:
    {{- include "_.selectorLabels" . | nindent 4 }}
