name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  # See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action
  - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
    env:
      cache-name: cache-node-modules
    with:
      path: ~/.npm
      key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      restore-keys: |
        ${{ runner.os }}-build-${{ env.cache-name }}-
        ${{ runner.os }}-build-
        ${{ runner.os }}-

  - name: Install Root NPM packages
    run: npm install
    shell: bash
