{{- if .Values.anycableGo.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "main.fullname" . }}-anycable-go
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: 'true'
    haproxy.router.openshift.io/timeout: 600s
spec:
  {{- if .Values.anycableGo.route.host }}
  host: {{ .Values.anycableGo.route.host }}
  {{- end }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name:
      {{ include "main.fullname" . }}-anycable-go
{{- end }}
