name: Enhancement Request
description: Suggest a new feature or improvement for this project
title: "[ER]: "
labels: ["enhancement"]
assignees: []   # Will be auto-assigned to PO via GitHub Action

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an enhancement!  
        Please provide as much detail as possible so the Product Owner can evaluate it.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short, descriptive title for this enhancement
      placeholder: "Add dark mode toggle"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: What exactly would you like to see improved or added?
      placeholder: "Explain the enhancement in detail..."
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: Value / Benefit
      description: Why is this enhancement valuable? Who benefits from it?
      placeholder: "This would reduce eye strain for users working at night..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other ways to solve the problem?
      placeholder: "Users can install browser extensions for dark mode, but..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Suggested Priority
      description: How urgent/important do you think this request is?
      options:
        - Low (Nice to have)
        - Medium (Should be done soon)
        - High (Blocks other work or users)
      default: 1   # Preselect "Medium"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or screenshots that might help
      placeholder: "Attach images, reference related issues, etc."
