template_publish:
  cron: "1 0 * * * America/Vancouver" # runs Every day at 12:01 AM (00:01) Vancouver time
  class: "TemplatePublishJob"
  queue: default
  active_job: false

remind_reviewers:
  cron: "30 8 * * 1 America/Vancouver" # Runs every Monday at 8:30 AM
  class: "RemindReviewerJob"
  queue: default
  active_job: false

send_batched_integration_mapping_notifications:
  cron: "0 * * * * America/Vancouver" # Runs every hour
  class: "SendBatchedIntegrationMappingNotificationsJob"
  queue: default
  active_job: false

cleanup_stuck_scans:
  cron: "0 */6 * * * America/Vancouver" # Runs every 6 hours
  class: "CleanupStuckScansJob"
  queue: default
  active_job: true

aws_credential_refresh:
  cron: "0 */2 * * * America/Vancouver" # Runs every 2 hours (more frequent refresh)
  class: "AwsCredentialRefreshJob"
  queue: default
  active_job: true

aws_credential_health_check:
  cron: "*/15 * * * * America/Vancouver" # Runs every 15 minutes for aggressive monitoring
  class: "AwsCredentialHealthCheckJob"
  queue: default
  active_job: true


