template_publish:
  cron: "1 0 * * * America/Vancouver" # runs Every day at 12:01 AM (00:01) Vancouver time
  class: "TemplatePublishJob"
  queue: default
  active_job: false

remind_reviewers:
  cron: "30 8 * * 1 America/Vancouver" # Runs every Monday at 8:30 AM
  class: "RemindReviewerJob"
  queue: default
  active_job: false

send_batched_integration_mapping_notifications:
  cron: "0 * * * * America/Vancouver" # Runs every hour
  class: "SendBatchedIntegrationMappingNotificationsJob"
  queue: default
  active_job: false

process_pending_virus_scans:
  cron: "*/15 * * * * America/Vancouver" # Runs every 15 minutes
  class: "ProcessPendingVirusScanJob"
  queue: default
  active_job: true
