{{- range .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ $.Values.appName }}-{{ .process }}"
  name: "{{ $.Values.appName }}-{{ .process }}"
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: "{{ $.Values.appName }}-{{ .process }}"
      deployment: "{{ $.Values.appName }}-{{ .process }}"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-secrets.env: '{{ printf "%s/%s-%s" $.Values.vaultNamespace $.Values.STAGE $.Values.appName}}'
        vault.hashicorp.com/agent-inject-template-secrets.env: |
          {{`{{- with secret "`}}{{ printf "%s/%s-%s" $.Values.vaultNamespace $.Values.STAGE $.Values.appName }}{{ `" -}}`}}
          {{`{{- range $k, $v := .Data.data }}`}}
          {{ `{{ $k }}={{ $v }}{{ end -}}` }}
          {{`{{- end }}`}}
        vault.hashicorp.com/agent-limits-cpu: "50m"
        vault.hashicorp.com/agent-limits-mem: "100Mi"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-requests-cpu: "10m"
        vault.hashicorp.com/agent-requests-mem: "25Mi"
        vault.hashicorp.com/auth-path: "auth/k8s-silver"
        vault.hashicorp.com/namespace: "platform-services"
        vault.hashicorp.com/role: '{{ $.Values.vaultNamespace }}'
      labels:
        app: "{{ $.Values.appName }}-{{ .process }}"
        deployment: "{{ $.Values.appName }}-{{ .process }}"
    spec:
      imagePullSecrets:
        - name: {{ $.Values.image.serviceAccountName }}
      containers:
        - name: {{ $.Values.appName }}-{{ .process }}
          imagePullPolicy: Always
          image: {{ $.Values.imageRepository }}/{{ $.Values.OPENSHIFT_NAMESPACE }}-{{ $.Values.STAGE }}/{{ $.Values.image.name }}:{{ $.Values.image.tag }}
          {{- if eq .process "web" }}
          volumeMounts:
            - name: log-volume
              mountPath: /app/log
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ha-postgres-crunchydb-pguser-postgres
                  key: uri
            - name: DATABASE_OPENSHIFT_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: ha-postgres-crunchydb-pguser-postgres
                  key: host
          {{- end }}
          envFrom:
            - configMapRef:
                name: app-environment-variables
            {{- if eq .process "web" }}
            - configMapRef:
                name: app-components-url
            - configMapRef:
                name: app-keycloak
            - configMapRef:
                name: app-web-variables
            {{- end }}
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: {{ .spec.containers.resources.limits.cpu }}
              memory: {{ .spec.containers.resources.limits.memory }}
            requests:
              cpu: {{ .spec.containers.resources.requests.cpu }}
              memory: {{ .spec.containers.resources.requests.memory }}
          {{- if .spec.containers.includeCommand }}
          command:
          - /bin/sh
          - '-c'
          args: {{ .spec.containers.args }}
          {{- end }} 
      {{- if eq .process "web" }}
          readinessProbe:
            httpGet:
              path: /up
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /up
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: compliance-log-pvc
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ $.Values.OPENSHIFT_NAMESPACE }}-vault
      serviceAccountName: {{ $.Values.OPENSHIFT_NAMESPACE }}-vault
      terminationGracePeriodSeconds: 30
---
 {{- end }}