apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.appName }}
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      importPolicy:
        scheduled: true