-- Restore missing indexes and foreign keys
-- Safe to run: CREATE INDEX CONCURRENTLY IF NOT EXISTS / ALTER TABLE ADD CONSTRAINT
-- Note: index_users_on_email intentionally excluded (pre-existing duplicates, not meaningful for BCSC auth)

-- ============================================================
-- INDEXES (121)
-- ============================================================

CREATE INDEX CONCURRENTLY IF NOT EXISTS index_aws_credentials_on_name ON aws_credentials USING btree (name);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_contractor_employees_on_contractor_id_and_employee_id ON contractor_employees USING btree (contractor_id, employee_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_contractor_employees_on_contractor_id ON contractor_employees USING btree (contractor_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_contractor_employees_on_employee_id ON contractor_employees USING btree (employee_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_contractor_imports_on_consumed_at ON contractor_imports USING btree (consumed_at);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_contractor_imports_on_contractor_id ON contractor_imports USING btree (contractor_id);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_contractor_imports_on_invite_code ON contractor_imports USING btree (invite_code);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_contractor_imports_on_invite_email_sent_at ON contractor_imports USING btree (invite_email_sent_at);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_contractor_imports_on_payload ON contractor_imports USING gin (payload);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_contractor_infos_on_contractor_id ON contractor_infos USING btree (contractor_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_contractor_onboards_on_contractor_id ON contractor_onboards USING btree (contractor_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_contractor_onboards_on_onboard_application_id ON contractor_onboards USING btree (onboard_application_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_contractors_on_contact_id ON contractors USING btree (contact_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_collaborators_on_collaboratorable ON collaborators USING btree (collaboratorable_type, collaboratorable_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_collaborators_on_user_id ON collaborators USING btree (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_contacts_on_contactable ON contacts USING btree (contactable_type, contactable_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_early_access_previews_on_previewer_id ON early_access_previews USING btree (previewer_id);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_early_access_previews_on_template_id_and_previewer_id ON early_access_previews USING btree (early_access_requirement_template_id, previewer_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_external_api_keys_on_jurisdiction_id ON external_api_keys USING btree (jurisdiction_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_external_api_keys_on_program_id ON external_api_keys USING btree (program_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_external_api_keys_on_sandbox_id ON external_api_keys USING btree (sandbox_id);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_external_api_keys_on_token ON external_api_keys USING btree (token);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_integration_mapping_notifications_on_notifiable ON integration_mapping_notifications USING btree (notifiable_type, notifiable_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_integration_mapping_notifications_on_template_version_id ON integration_mapping_notifications USING btree (template_version_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_integration_mappings_on_jurisdiction_id ON integration_mappings USING btree (jurisdiction_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_integration_mappings_on_template_version_id ON integration_mappings USING btree (template_version_id);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_jtvcs_unique_on_jurisdiction_template_sandbox ON jurisdiction_template_version_customizations USING btree (jurisdiction_id, template_version_id, COALESCE(sandbox_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_jurisdiction_memberships_on_jurisdiction_id ON jurisdiction_memberships USING btree (jurisdiction_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_jurisdiction_memberships_on_user_id ON jurisdiction_memberships USING btree (user_id);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_jurisdictions_on_prefix ON jurisdictions USING btree (prefix);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_jurisdictions_on_regional_district_id ON jurisdictions USING btree (regional_district_id);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_jurisdictions_on_slug ON jurisdictions USING btree (slug);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS meui_composite_index ON mechanical_energy_use_intensity_references USING btree (hdd, conditioned_space_percent, step, conditioned_space_area);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_applications_on_activity_id ON permit_applications USING btree (activity_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_applications_on_audience_type_id ON permit_applications USING btree (audience_type_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_applications_on_jurisdiction_id ON permit_applications USING btree (jurisdiction_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_applications_on_permit_type_id ON permit_applications USING btree (permit_type_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_applications_on_program_id ON permit_applications USING btree (program_id);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_permit_applications_on_program_id_and_number ON permit_applications USING btree (program_id, number);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_applications_on_sandbox_id ON permit_applications USING btree (sandbox_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_applications_on_submission_type_id ON permit_applications USING btree (submission_type_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_applications_on_submission_variant_id ON permit_applications USING btree (submission_variant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_applications_on_template_version_id ON permit_applications USING btree (template_version_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_applications_on_user_group_type_id ON permit_applications USING btree (user_group_type_id);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_block_statuses_on_app_id_and_block_id_and_collab_type ON permit_block_statuses USING btree (permit_application_id, requirement_block_id, collaboration_type);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_block_statuses_on_permit_application_id ON permit_block_statuses USING btree (permit_application_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_classifications_on_parent_id ON permit_classifications USING btree (parent_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_collaborations_on_collaboration_type ON permit_collaborations USING btree (collaboration_type);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_collaborations_on_collaborator_id ON permit_collaborations USING btree (collaborator_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_collaborations_on_collaborator_type ON permit_collaborations USING btree (collaborator_type);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_collaborations_on_permit_application_id ON permit_collaborations USING btree (permit_application_id);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_permit_collaborations_on_unique_columns ON permit_collaborations USING btree (permit_application_id, collaborator_id, collaboration_type, collaborator_type, assigned_requirement_block_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_type_required_steps_on_jurisdiction_id ON permit_type_required_steps USING btree (jurisdiction_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_type_required_steps_on_permit_type_id ON permit_type_required_steps USING btree (permit_type_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_type_submission_contacts_on_jurisdiction_id ON permit_type_submission_contacts USING btree (jurisdiction_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_permit_type_submission_contacts_on_permit_type_id ON permit_type_submission_contacts USING btree (permit_type_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_preferences_on_user_id ON preferences USING btree (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_program_memberships_on_program_id ON program_memberships USING btree (program_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_program_memberships_on_user_id ON program_memberships USING btree (user_id);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_program_memberships_on_user_id_and_program_id ON program_memberships USING btree (user_id, program_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_requirement_blocks_on_discarded_at ON requirement_blocks USING btree (discarded_at);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_requirement_blocks_on_name_and_first_nations ON requirement_blocks USING btree (name, first_nations);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_requirement_blocks_on_sku ON requirement_blocks USING btree (sku);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_requirement_template_sections_on_copied_from_id ON requirement_template_sections USING btree (copied_from_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_requirement_template_sections_on_requirement_template_id ON requirement_template_sections USING btree (requirement_template_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_requirement_templates_on_activity_id ON requirement_templates USING btree (activity_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_requirement_templates_on_assignee_id ON requirement_templates USING btree (assignee_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_requirement_templates_on_copied_from_id ON requirement_templates USING btree (copied_from_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_requirement_templates_on_discarded_at ON requirement_templates USING btree (discarded_at);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_requirement_templates_on_permit_type_id ON requirement_templates USING btree (permit_type_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_requirement_templates_on_program_id ON requirement_templates USING btree (program_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_requirement_templates_on_submission_type_id ON requirement_templates USING btree (submission_type_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_requirement_templates_on_submission_variant_id ON requirement_templates USING btree (submission_variant_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_requirement_templates_on_type ON requirement_templates USING btree (type);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_requirements_on_requirement_block_id ON requirements USING btree (requirement_block_id);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_revision_reasons_on_reason_code ON revision_reasons USING btree (reason_code);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_revision_reasons_on_site_configuration_id ON revision_reasons USING btree (site_configuration_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_revision_requests_on_submission_version_id ON revision_requests USING btree (submission_version_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_revision_requests_on_user_id ON revision_requests USING btree (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_sandboxes_on_jurisdiction_id ON sandboxes USING btree (jurisdiction_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_step_code_checklists_on_status ON step_code_checklists USING btree (status);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_step_code_checklists_on_step_code_id ON step_code_checklists USING btree (step_code_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_step_code_checklists_on_step_requirement_id ON step_code_checklists USING btree (step_requirement_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_step_code_data_entries_on_step_code_id ON step_code_data_entries USING btree (step_code_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_step_codes_on_permit_application_id ON step_codes USING btree (permit_application_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_step_codes_on_virus_scan_completed_at ON step_codes USING btree (virus_scan_completed_at);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_step_codes_on_virus_scan_status ON step_codes USING btree (virus_scan_status);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_submission_versions_on_permit_application_id ON submission_versions USING btree (permit_application_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_support_requests_on_linked_application_id ON support_requests USING btree (linked_application_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_support_requests_on_parent_application_id ON support_requests USING btree (parent_application_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_support_requests_on_requested_by_id ON support_requests USING btree (requested_by_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_supporting_documents_on_permit_application_id ON supporting_documents USING btree (permit_application_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_supporting_documents_on_submission_version_id ON supporting_documents USING btree (submission_version_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_supporting_documents_on_virus_scan_completed_at ON supporting_documents USING btree (virus_scan_completed_at);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_supporting_documents_on_virus_scan_status ON supporting_documents USING btree (virus_scan_status);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_taggings_on_context ON taggings USING btree (context);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_taggings_on_tag_id ON taggings USING btree (tag_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_taggings_on_taggable_id ON taggings USING btree (taggable_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_taggings_on_taggable_type ON taggings USING btree (taggable_type);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_taggings_on_taggable_type_and_taggable_id ON taggings USING btree (taggable_type, taggable_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_taggings_on_tagger_id ON taggings USING btree (tagger_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_taggings_on_tagger_id_and_tagger_type ON taggings USING btree (tagger_id, tagger_type);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_taggings_on_tagger_type_and_tagger_id ON taggings USING btree (tagger_type, tagger_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_taggings_on_tenant ON taggings USING btree (tenant);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS taggings_idx ON taggings USING btree (tag_id, taggable_id, taggable_type, context, tagger_id, tagger_type);
CREATE INDEX CONCURRENTLY IF NOT EXISTS taggings_idy ON taggings USING btree (taggable_id, taggable_type, tagger_id, context);
CREATE INDEX CONCURRENTLY IF NOT EXISTS taggings_taggable_context_idx ON taggings USING btree (taggable_id, taggable_type, context);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_tags_on_name ON tags USING btree (name);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_template_section_blocks_on_requirement_block_id ON template_section_blocks USING btree (requirement_block_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_template_versions_on_deprecated_by_id ON template_versions USING btree (deprecated_by_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_template_versions_on_requirement_template_id ON template_versions USING btree (requirement_template_id);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS tedi_composite_index ON thermal_energy_demand_intensity_references USING btree (hdd, step);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_user_addresses_on_user_id ON user_addresses USING btree (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_user_license_agreements_on_agreement_id ON user_license_agreements USING btree (agreement_id);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_users_on_confirmation_token ON users USING btree (confirmation_token);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_users_on_discarded_at ON users USING btree (discarded_at);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_users_on_invitation_token ON users USING btree (invitation_token);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_users_on_invited_by ON users USING btree (invited_by_type, invited_by_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS index_users_on_invited_by_id ON users USING btree (invited_by_id);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_users_on_omniauth_provider_and_omniauth_uid ON users USING btree (omniauth_provider, omniauth_uid);
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS index_users_on_reset_password_token ON users USING btree (reset_password_token);

-- ============================================================
-- FOREIGN KEYS (85)
-- ============================================================

DO $$ BEGIN ALTER TABLE allowlisted_jwts ADD CONSTRAINT fk_rails_77afa78cd5 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE application_assignments ADD CONSTRAINT fk_rails_0fea289ef2 FOREIGN KEY (permit_application_id) REFERENCES permit_applications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE application_assignments ADD CONSTRAINT fk_rails_50a05b07f7 FOREIGN KEY (user_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE audit_logs ADD CONSTRAINT fk_rails_1f26bc34ae FOREIGN KEY (user_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE collaborators ADD CONSTRAINT fk_rails_3d4aaacbb1 FOREIGN KEY (user_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE contractor_employees ADD CONSTRAINT fk_rails_a4665164de FOREIGN KEY (employee_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE contractor_employees ADD CONSTRAINT fk_rails_f2b35cf1eb FOREIGN KEY (contractor_id) REFERENCES contractors(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE contractor_infos ADD CONSTRAINT fk_rails_407b274d57 FOREIGN KEY (contractor_id) REFERENCES contractors(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE contractor_onboards ADD CONSTRAINT fk_rails_1a2f3fa1b1 FOREIGN KEY (onboard_application_id) REFERENCES permit_applications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE contractor_onboards ADD CONSTRAINT fk_rails_232641b22f FOREIGN KEY (deactivated_by) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE contractor_onboards ADD CONSTRAINT fk_rails_bd67fdd113 FOREIGN KEY (suspended_by) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE contractor_onboards ADD CONSTRAINT fk_rails_c00af1cf3c FOREIGN KEY (contractor_id) REFERENCES contractors(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE contractors ADD CONSTRAINT fk_rails_201e9c85fc FOREIGN KEY (contact_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE early_access_previews ADD CONSTRAINT fk_rails_6f9f92b507 FOREIGN KEY (previewer_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE external_api_keys ADD CONSTRAINT fk_rails_178355b0fe FOREIGN KEY (jurisdiction_id) REFERENCES jurisdictions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE external_api_keys ADD CONSTRAINT fk_rails_1bfd4c6b26 FOREIGN KEY (program_id) REFERENCES programs(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE external_api_keys ADD CONSTRAINT fk_rails_edf4726e73 FOREIGN KEY (sandbox_id) REFERENCES sandboxes(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE integration_mapping_notifications ADD CONSTRAINT fk_rails_19c7baa5a1 FOREIGN KEY (template_version_id) REFERENCES template_versions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE integration_mappings ADD CONSTRAINT fk_rails_1793cb12c5 FOREIGN KEY (template_version_id) REFERENCES template_versions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE integration_mappings ADD CONSTRAINT fk_rails_b64ab7a4ad FOREIGN KEY (jurisdiction_id) REFERENCES jurisdictions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE jurisdiction_memberships ADD CONSTRAINT fk_rails_aa4540c1d1 FOREIGN KEY (user_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE jurisdiction_memberships ADD CONSTRAINT fk_rails_f5ab6076d0 FOREIGN KEY (jurisdiction_id) REFERENCES jurisdictions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE jurisdiction_template_version_customizations ADD CONSTRAINT fk_rails_5506d8f962 FOREIGN KEY (jurisdiction_id) REFERENCES jurisdictions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE jurisdiction_template_version_customizations ADD CONSTRAINT fk_rails_f69653f582 FOREIGN KEY (sandbox_id) REFERENCES sandboxes(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE jurisdiction_template_version_customizations ADD CONSTRAINT fk_rails_f75ad694c2 FOREIGN KEY (template_version_id) REFERENCES template_versions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE jurisdictions ADD CONSTRAINT fk_rails_c1d8da19d0 FOREIGN KEY (regional_district_id) REFERENCES jurisdictions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_applications ADD CONSTRAINT fk_rails_1829aa9a9e FOREIGN KEY (submission_type_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_applications ADD CONSTRAINT fk_rails_2b6483422f FOREIGN KEY (program_id) REFERENCES programs(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_applications ADD CONSTRAINT fk_rails_6638b926d4 FOREIGN KEY (permit_type_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_applications ADD CONSTRAINT fk_rails_690f9d7fbd FOREIGN KEY (template_version_id) REFERENCES template_versions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_applications ADD CONSTRAINT fk_rails_cc1836a677 FOREIGN KEY (submission_variant_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_applications ADD CONSTRAINT fk_rails_e4fcaf99da FOREIGN KEY (audience_type_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_applications ADD CONSTRAINT fk_rails_f239005ad0 FOREIGN KEY (user_group_type_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_applications ADD CONSTRAINT fk_rails_f80aa8d423 FOREIGN KEY (sandbox_id) REFERENCES sandboxes(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_applications ADD CONSTRAINT fk_rails_fbf006c21b FOREIGN KEY (activity_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_applications ADD CONSTRAINT fk_rails_fd463eee2d FOREIGN KEY (jurisdiction_id) REFERENCES jurisdictions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_block_statuses ADD CONSTRAINT fk_rails_1067ff65ff FOREIGN KEY (permit_application_id) REFERENCES permit_applications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_classifications ADD CONSTRAINT fk_rails_ab39b030cd FOREIGN KEY (parent_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_collaborations ADD CONSTRAINT fk_rails_11be45db37 FOREIGN KEY (collaborator_id) REFERENCES collaborators(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_collaborations ADD CONSTRAINT fk_rails_5e4ceade25 FOREIGN KEY (permit_application_id) REFERENCES permit_applications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_type_required_steps ADD CONSTRAINT fk_rails_68df363b6e FOREIGN KEY (permit_type_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_type_required_steps ADD CONSTRAINT fk_rails_83fdbe4069 FOREIGN KEY (jurisdiction_id) REFERENCES jurisdictions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_type_submission_contacts ADD CONSTRAINT fk_rails_9cfcfce6b0 FOREIGN KEY (permit_type_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE permit_type_submission_contacts ADD CONSTRAINT fk_rails_e8640fe8fc FOREIGN KEY (jurisdiction_id) REFERENCES jurisdictions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE preferences ADD CONSTRAINT fk_rails_87f1c9c7bd FOREIGN KEY (user_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE program_classification_memberships ADD CONSTRAINT fk_rails_2e75452791 FOREIGN KEY (program_membership_id) REFERENCES program_memberships(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE program_classification_memberships ADD CONSTRAINT fk_rails_41716a55bb FOREIGN KEY (submission_type_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE program_classification_memberships ADD CONSTRAINT fk_rails_d416383360 FOREIGN KEY (user_group_type_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE program_memberships ADD CONSTRAINT fk_rails_21b1e7f699 FOREIGN KEY (program_id) REFERENCES programs(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE program_memberships ADD CONSTRAINT fk_rails_b7469a5f30 FOREIGN KEY (user_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE requirement_template_sections ADD CONSTRAINT fk_rails_82efafb61a FOREIGN KEY (requirement_template_id) REFERENCES requirement_templates(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE requirement_template_sections ADD CONSTRAINT fk_rails_cad1b0df48 FOREIGN KEY (copied_from_id) REFERENCES requirement_template_sections(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE requirement_templates ADD CONSTRAINT fk_rails_01a2ea6b44 FOREIGN KEY (assignee_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE requirement_templates ADD CONSTRAINT fk_rails_1daa6d3c4b FOREIGN KEY (copied_from_id) REFERENCES requirement_templates(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE requirement_templates ADD CONSTRAINT fk_rails_28deb4ce84 FOREIGN KEY (audience_type_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE requirement_templates ADD CONSTRAINT fk_rails_33cef8bd4e FOREIGN KEY (program_id) REFERENCES programs(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE requirement_templates ADD CONSTRAINT fk_rails_6180af641b FOREIGN KEY (submission_variant_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE requirement_templates ADD CONSTRAINT fk_rails_7d19a6040c FOREIGN KEY (submission_type_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE requirement_templates ADD CONSTRAINT fk_rails_8585ee0e34 FOREIGN KEY (permit_type_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE requirement_templates ADD CONSTRAINT fk_rails_b94e801aec FOREIGN KEY (activity_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE requirement_templates ADD CONSTRAINT fk_rails_c73518da2f FOREIGN KEY (user_group_type_id) REFERENCES permit_classifications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE requirements ADD CONSTRAINT fk_rails_644d323f2d FOREIGN KEY (requirement_block_id) REFERENCES requirement_blocks(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE revision_reasons ADD CONSTRAINT fk_rails_52d0a2e1ea FOREIGN KEY (site_configuration_id) REFERENCES site_configurations(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE revision_requests ADD CONSTRAINT fk_rails_640a8a44df FOREIGN KEY (user_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE revision_requests ADD CONSTRAINT fk_rails_8afa6909e1 FOREIGN KEY (submission_version_id) REFERENCES submission_versions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE sandboxes ADD CONSTRAINT fk_rails_c15f817c17 FOREIGN KEY (jurisdiction_id) REFERENCES jurisdictions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE site_configurations ADD CONSTRAINT fk_rails_991b422bb1 FOREIGN KEY (small_scale_requirement_template_id) REFERENCES requirement_templates(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE step_code_building_characteristics_summaries ADD CONSTRAINT fk_rails_990e28543b FOREIGN KEY (step_code_checklist_id) REFERENCES step_code_checklists(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE step_code_checklists ADD CONSTRAINT fk_rails_4783875c89 FOREIGN KEY (step_code_id) REFERENCES step_codes(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE step_code_checklists ADD CONSTRAINT fk_rails_b3f2546f18 FOREIGN KEY (step_requirement_id) REFERENCES permit_type_required_steps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE step_code_data_entries ADD CONSTRAINT fk_rails_77d826175c FOREIGN KEY (step_code_id) REFERENCES step_codes(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE step_codes ADD CONSTRAINT fk_rails_39537b66ec FOREIGN KEY (permit_application_id) REFERENCES permit_applications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE submission_versions ADD CONSTRAINT fk_rails_f45b483fef FOREIGN KEY (permit_application_id) REFERENCES permit_applications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE support_requests ADD CONSTRAINT fk_rails_0df8ac23dd FOREIGN KEY (linked_application_id) REFERENCES permit_applications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE support_requests ADD CONSTRAINT fk_rails_10c6281cc3 FOREIGN KEY (requested_by_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE support_requests ADD CONSTRAINT fk_rails_d314f55387 FOREIGN KEY (parent_application_id) REFERENCES permit_applications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE supporting_documents ADD CONSTRAINT fk_rails_274c48ba0a FOREIGN KEY (permit_application_id) REFERENCES permit_applications(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE supporting_documents ADD CONSTRAINT fk_rails_778a3ff237 FOREIGN KEY (submission_version_id) REFERENCES submission_versions(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE taggings ADD CONSTRAINT fk_rails_9fcd2e236b FOREIGN KEY (tag_id) REFERENCES tags(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE template_section_blocks ADD CONSTRAINT fk_rails_4cd8255710 FOREIGN KEY (requirement_template_section_id) REFERENCES requirement_template_sections(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE template_section_blocks ADD CONSTRAINT fk_rails_b8a89e1da0 FOREIGN KEY (requirement_block_id) REFERENCES requirement_blocks(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE template_versions ADD CONSTRAINT fk_rails_a72075f99b FOREIGN KEY (requirement_template_id) REFERENCES requirement_templates(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE template_versions ADD CONSTRAINT fk_rails_fa8b1e9644 FOREIGN KEY (deprecated_by_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE user_addresses ADD CONSTRAINT fk_rails_2718c5b54a FOREIGN KEY (user_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE user_license_agreements ADD CONSTRAINT fk_rails_983a0a7234 FOREIGN KEY (agreement_id) REFERENCES end_user_license_agreements(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
