name: Auto Assign New Issues

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign based on template
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.issue.labels.map(l => l.name);
            
            // Map templates to owners
            const assigneeMap = {
              "bug": "BAuger-BC",          // PM GitHub username
              "enhancement": "milo-dxcas"   // PO GitHub username
            };

            // Find first matching label
            for (const label of labels) {
              if (assigneeMap[label]) {
                await github.rest.issues.addAssignees({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  assignees: [assigneeMap[label]]
                });
                console.log(`Assigned to ${assigneeMap[label]} for label ${label}`);
                break;
              }
            }
