name: Deploy Dev Environment

on:
  push:
    branches:
    - main
    paths-ignore:
    - '.github/**'
    - 'docs/**'

env:
  GITHUB_REGISTRY: ghcr.io
  ARTIFACTORY_REGISTRY: artifacts.developer.gov.bc.ca

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: write
  security-events: write

jobs:
  build-push-app-ghcr:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Set Deployment Timestamp
      run: echo "DEPLOYMENT_TIMESTAMP=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

    - name: Build and Push
      uses: egose/actions/docker-build-push@46d589997e49cae4a8a3d06644ae8b04351a30f2
      with:
        registry-url: ${{ env.GITHUB_REGISTRY }}
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        image-name: bcgov/hesp-app
        docker-context: .
        docker-file: devops/docker/app/Dockerfile
        docker-args: |
          DEPLOYMENT_TIMESTAMP=${{ env.DEPLOYMENT_TIMESTAMP }}
          VITE_ENABLE_TEMPLATE_FORCE_PUBLISH=true
        metadata-tags: |
          type=ref,event=branch
          type=sha,format=long,prefix=,suffix=

  # build-push-app-artifacts:
  #   runs-on: ubuntu-22.04
  #   timeout-minutes: 20
  #   continue-on-error: true
  #   steps:
  #   - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
  #   - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

  #   - name: Setup Tools
  #     uses: ./.github/actions/setup-tools

  #   - name: Set Deployment Timestamp
  #     run: echo "DEPLOYMENT_TIMESTAMP=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

  #   - name: Build and Push
  #     uses: egose/actions/docker-build-push@46d589997e49cae4a8a3d06644ae8b04351a30f2
  #     with:
  #       registry-url: ${{ env.ARTIFACTORY_REGISTRY }}
  #       registry-username: ${{ secrets.ARTIFACTORY_USERNAME }}
  #       registry-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
  #       image-name: bbfc-dev/hesp-dev
  #       docker-context: .
  #       docker-file: devops/docker/app/Dockerfile
  #       docker-args: |
  #         DEPLOYMENT_TIMESTAMP=${{ env.DEPLOYMENT_TIMESTAMP }}
  #       metadata-tags: |
  #         type=sha,format=long,prefix=,suffix=

  deploy:
    needs: [build-push-app-ghcr]
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      contents: read
    environment:
      name: dev
      url: https://dev-hesp.apps.silver.devops.gov.bc.ca

    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

    - name: Authenticate and set context
      uses: redhat-actions/oc-login@dfbd9912672664f9df2023c1c16e07bcf306043c
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        namespace: ${{ vars.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: true

    - name: Deploy apps with Helm chart
      run: |
        make upgrade NAMESPACE=${{ vars.OPENSHIFT_NAMESPACE }} IMAGE_TAG=${{ github.sha }}
        kubectl rollout status deployment/hesp-app
      working-directory: ./helm/main
