name: Build and Push Docker Image to Artifactory

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch Name"
        required: true
        default: "main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build & Push Docker Image to Artifactory
    environment: dev

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          lfs: true

      # Step 2: Log in to Artifactory Docker Registry
      - name: Log in to Artifactory
        run: |
          echo "${{ secrets.ARTIFACTORY_PASSWORD }}" | docker login https://artifacts.developer.gov.bc.ca:443/artifactory -u "${{ secrets.ARTIFACTORY_USERNAME }}" --password-stdin
        env:
          DOCKER_CONFIG: /tmp/docker-config
      
      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build \
            --file ./devops/docker/app/Dockerfile \
            --tag https://artifacts.developer.gov.bc.ca:443/artifactory/bbfc-local/permit-app:latest \
            --tag https://artifacts.developer.gov.bc.ca:443/artifactory/bbfc-local/permit-app:${{ github.sha }} \
            .
      
      # Step 4: Push the Docker image to Artifactory
      - name: Push Docker Image to Artifactory
        run: |
          docker push https://artifacts.developer.gov.bc.ca:443/artifactory/bbfc-local/permit-app:latest
          docker push https://artifacts.developer.gov.bc.ca:443/artifactory/bbfc-local/permit-app:${{ github.sha }}

      - name: Log out from Docker
        run: docker logout ${{ secrets.ARTIFACTORY_URL }}
