name: Build and Publish ClamAV Image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-clamav.yml
      - devops/docker/clamav/**

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: bcgov/hesp-clamav

jobs:
  build-push-clamav:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # Grab appVersion from the subchart
      - id: chart-version
        run: |
          echo "appVersion=$(yq '.appVersion' _clamav/Chart.yaml)" >> $GITHUB_OUTPUT

      # Build & Push image with multiple tags
      - name: Build and Push
        uses: egose/actions/docker-build-push@46d589997e49cae4a8a3d06644ae8b04351a30f2
        with:
          registry-url: ${{ env.GITHUB_REGISTRY }}
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ env.IMAGE_NAME }}
          docker-context: devops/docker/clamav
          docker-file: devops/docker/clamav/Dockerfile
          metadata-tags: |
            type=ref,event=branch              # → :main
            type=sha,format=short              # → :abcd123
            type=raw,value=${{ steps.chart-version.outputs.appVersion }}   # → :1.0.0
