name: Build and Push Docker Image to Artifactory

on:
  push:
    branches:
    - test
    paths:
      - app/**
      - config/**
      - db/**
      - eulas/**
      - lib/**
      - public/**
      - spec/**
      - swagger/**
      - config.ru
      - Gemfile
      - Gemfile.lock
      - package-lock.json
      - package.json
      - Rakefile

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build & Push Docker Image to Artifactory
    environment: test

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          lfs: true

      # Step 2: Login to Artifactory
      - name: Login to Artifactory
        run: docker login artifacts.developer.gov.bc.ca -u ${{ secrets.ARTIFACTORY_USERNAME }} -p ${{ secrets.ARTIFACTORY_PASSWORD }}
      
      # Step 3: Build Image
      - name: Build Docker Image
        run: docker build -t energy-app -f ./devops/docker/app/Dockerfile .

      # Step 4: Tag the Image
      - name: Tag Docker Image
        run: docker tag energy-app artifacts.developer.gov.bc.ca/bbfc-test/energy-app:latest
      
      # Step 5: Push the Docker image to Artifactory
      - name: Push Image to Artifactory
        run: docker push artifacts.developer.gov.bc.ca/bbfc-test/energy-app:latest

      # Step 6: Logout
      - name: Log out from Docker
        run: docker logout artifacts.developer.gov.bc.ca
